name: Snow Triggered Deploy

on:
  repository_dispatch:
    types: [snow-trigger]

jobs:
  print-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Print ServiceNow Trigger Message
        run: echo "GitHub Actions pipeline triggered by ServiceNow deploy event!"
