name: Snow Triggered Deploy

on:
  repository_dispatch:
    types: [snow-trigger]

jobs:
  print-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Print Change Request Number
        run: echo "Change Request Number is ${{ github.event.client_payload.number }}"

      - name: Print ServiceNow Trigger Message
        run: echo "GitHub Actions pipeline triggered by ServiceNow deploy event!"
